---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: bento-centos-7-vagrant
    box: bento/centos-7
    cpus: 2
    memory: 4096
provisioner:
  name: ansible
  options:
    become: true
  lint:
    name: ansible-lint
    options:
      R: true
scenario:
  name: vagrant
verifier:
  name: testinfra
  directory: ../tests
  options:
    verbose: true
  lint:
    name: flake8
